server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/file?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: root

  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html

cfg:
  root-path: /mnt/sda1/files

#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: jame.work.filesserver.entity
#  mapper-locations: classpath*:mapper/*.xml
